#include "SkyAtmosphereCommon.hlsl"

#pragma kernel kComputeTransmittanceLut
#define TRANSMITTANCE_STEPS 40

StructuredBuffer<SkyAtmosphereParameters> _SkyAtmosphereParametersBuffer;
RWTexture2D<float4> _TransmittanceLut;


float3 GetTransmittanceToBoundary(in SkyAtmosphereParameters skyAtmosphereParameters, float mu, float r)
{
    float distance = DistanceToTopAtmosphereBoundary(GetAtmosphereTop(skyAtmosphereParameters), r, mu);
    float dx = distance / TRANSMITTANCE_STEPS;

    float3 result = 0.0f;
    for (int i = 0; i <= TRANSMITTANCE_STEPS; ++i)
    {
        float d_i = i * dx;
        float r_i = sqrt(d_i * d_i + 2.0 * r * mu * d_i + r * r);
        float h_i = r_i - GetAtmosphereBottom(skyAtmosphereParameters);
        float intensity_rayleigh_i = GetRayleighIntensity(skyAtmosphereParameters,
                                                          h_i);
        float intensity_mie_i = GetMieIntensity(skyAtmosphereParameters,
                                                h_i);
        float intensity_ozone_i = GetOzoneIntensity(skyAtmosphereParameters,
                                                    h_i);
        float weight_i = (i == 0 || i == TRANSMITTANCE_STEPS) ? 0.5f : 1.0f;
        result += skyAtmosphereParameters.rayleighScattering.xyz * intensity_rayleigh_i * weight_i * dx;
        result += (skyAtmosphereParameters.mieScatteringPacked.xyz + skyAtmosphereParameters.mieAbsorption.xyz) *
            intensity_mie_i * weight_i * dx;
        result += skyAtmosphereParameters.ozoneAbsorption.xyz * intensity_ozone_i * weight_i * dx;
    }
    return exp(-result);
}


[numthreads(16, 16, 1)]
void kComputeTransmittanceLut(uint3 id : SV_DispatchThreadID)
{
    SkyAtmosphereParameters skyAtmosphereParameters = _SkyAtmosphereParametersBuffer[0];

    uint2 size;
    _TransmittanceLut.GetDimensions(size.x, size.y);
    if (id.x >= size.x || id.y >= size.y)
    {
        return;
    }

    float2 uv = (float2(id.xy) + 0.5f) / size.xy;
    float r, mu;
    GetRMuFromTransmittanceTextureUv(
        GetAtmosphereBottom(skyAtmosphereParameters), GetAtmosphereTop(skyAtmosphereParameters),
        uv, size.x, size.y,
        r, mu);

    float3 transmittance = GetTransmittanceToBoundary(skyAtmosphereParameters, mu, r);
    _TransmittanceLut[id.xy] = float4(transmittance, 1.0f);
}
